INSERT INTO user_info (userID, userName, passWord, optionalBool) VALUES (100, "Jerry", "samplepw", false);
INSERT INTO user_info (userID, userName, passWord, optionalBool) VALUES (101, "Marlee", "samplepw", false);
INSERT INTO user_info (userID, userName, passWord, optionalBool) VALUES (102, "Thad", "samplepw", false);
INSERT INTO user_info (userID, userName, passWord, optionalBool) VALUES (104, "Lucy", "samplepw", false);

INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	sail	",	0	,	1	,	1	,	100	,	1000	,	10000	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	scene	",	0	,	1	,	1	,	101	,	1001	,	10001	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	scrub	",	0	,	1	,	1	,	102	,	1002	,	10002	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	shade	",	0	,	1	,	1	,	103	,	1003	,	10003	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	shaky	",	0	,	1	,	1	,	104	,	1004	,	10004	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	ship	",	0	,	1	,	1	,	105	,	1005	,	10005	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	shore	",	0	,	2	,	1	,	106	,	1006	,	10006	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	silky	",	0	,	2	,	1	,	107	,	1007	,	10007	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	sink	",	0	,	2	,	1	,	108	,	1008	,	10008	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	slide	",	0	,	2	,	1	,	109	,	1009	,	10009	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	slip	",	0	,	2	,	1	,	110	,	1010	,	10010	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	sniff	",	0	,	2	,	1	,	111	,	1011	,	10011	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	soapy	",	0	,	3	,	1	,	112	,	1012	,	10012	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	sparkle	",	0	,	3	,	1	,	113	,	1013	,	10013	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	spotted	",	0	,	3	,	1	,	114	,	1014	,	10014	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	spring	",	0	,	3	,	1	,	115	,	1015	,	10015	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	stare	",	0	,	3	,	1	,	116	,	1016	,	10016	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	summer	",	0	,	3	,	2	,	117	,	1017	,	10017	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	supplies	",	0	,	3	,	2	,	118	,	1018	,	10018	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	Ability	",	1	,	4	,	2	,	119	,	1019	,	10019	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	absorb	",	1	,	4	,	2	,	120	,	1020	,	10020	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	accuse	",	1	,	4	,	2	,	121	,	1021	,	10021	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	act	",	1	,	4	,	2	,	122	,	1022	,	10022	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	active	",	1	,	4	,	2	,	123	,	1023	,	10023	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	actual	",	1	,	4	,	2	,	124	,	1024	,	10024	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	adopt	",	1	,	5	,	2	,	125	,	1025	,	10025	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	advantage	",	1	,	5	,	2	,	126	,	1026	,	10026	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	advice	",	1	,	5	,	2	,	127	,	1027	,	10027	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	ambition	",	1	,	5	,	2	,	128	,	1028	,	10028	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	ancient	",	1	,	5	,	2	,	129	,	1029	,	10029	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	approach	",	1	,	5	,	2	,	130	,	1030	,	10030	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	arrange	",	2	,	5	,	2	,	131	,	1031	,	10031	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	arctic	",	2	,	6	,	2	,	132	,	1032	,	10032	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	attitude	",	2	,	6	,	2	,	133	,	1033	,	10033	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	attract	",	2	,	6	,	2	,	134	,	1034	,	10034	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	average	",	2	,	6	,	2	,	135	,	1035	,	10035	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	avoid	",	2	,	6	,	2	,	136	,	1036	,	10036	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	alculate	",	2	,	6	,	2	,	137	,	1037	,	10037	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	capable	",	2	,	6	,	2	,	138	,	1038	,	10038	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	captivity	",	2	,	7	,	2	,	139	,	1039	,	10039	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	carefree	",	2	,	7	,	2	,	140	,	1040	,	10040	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	century	",	2	,	7	,	2	,	141	,	1041	,	10041	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	chamber	",	2	,	7	,	2	,	142	,	1042	,	10042	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	circular	",	2	,	7	,	3	,	143	,	1043	,	10043	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	coax	",	2	,	7	,	3	,	144	,	1044	,	10044	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	column	",	2	,	7	,	3	,	145	,	1045	,	10045	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	communicate	",	2	,	8	,	3	,	146	,	1046	,	10046	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	competition	",	2	,	8	,	3	,	147	,	1047	,	10047	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	complete	",	2	,	8	,	3	,	148	,	1048	,	10048	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	concentrate	",	2	,	8	,	3	,	149	,	1049	,	10049	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	concern	",	2	,	8	,	3	,	150	,	1050	,	10050	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	conclude	",	2	,	8	,	3	,	151	,	1051	,	10051	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	confuse	",	3	,	8	,	3	,	152	,	1052	,	10052	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	congratulate	",	3	,	8	,	3	,	153	,	1053	,	10053	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	considerable	",	3	,	9	,	3	,	154	,	1054	,	10054	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	content	",	3	,	9	,	3	,	155	,	1055	,	10055	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	contribute	",	3	,	9	,	3	,	156	,	1056	,	10056	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	crafty	",	3	,	9	,	3	,	157	,	1057	,	10057	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	create	",	3	,	9	,	3	,	158	,	1058	,	10058	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	peculiar	",	3	,	9	,	3	,	159	,	1059	,	10059	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	peer	",	3	,	9	,	3	,	160	,	1060	,	10060	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	permit	",	3	,	10	,	3	,	161	,	1061	,	10061	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	plead	",	3	,	10	,	4	,	162	,	1062	,	10062	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	plentiful	",	3	,	10	,	4	,	163	,	1063	,	10063	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	pointless	",	3	,	10	,	4	,	164	,	1064	,	10064	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	portion	",	3	,	10	,	4	,	165	,	1065	,	10065	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	practice	",	3	,	11	,	4	,	166	,	1066	,	10066	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	precious	",	3	,	11	,	4	,	167	,	1067	,	10067	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	prefer	",	3	,	11	,	4	,	168	,	1068	,	10068	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	prepare	",	3	,	11	,	4	,	169	,	1069	,	10069	,	FALSE)	;
INSERT	INTO	vocab_content	(word,	grade,	subject,	listNumber,	dayCount,	weekCount,	monthCount,	optionalBOOL)	VALUES	("	proceed	",	3	,	11	,	4	,	170	,	1070	,	10070	,	FALSE)	;

INSERT	INTO list_record	(listNumber	, subject,	email,	sms,	grade,	frequency,	optionalBool)	VALUES	(	100	,	"ELA"	,	"justincarlson7@gmail.com",	"919-323-6782",	0,	"daily",	FALSE);
INSERT	INTO list_record	(listNumber	, subject,	email,	sms,	grade,	frequency,	optionalBool)	VALUES	(	200	,	"Math"	,	"justincarlson7@gmail.com",	"919-880-8005",	2,	"weekly",	FALSE);
INSERT	INTO list_record	(listNumber	,subject,	email,	sms,	grade,	frequency,	optionalBool)	VALUES	(	300	,	"Math"	,	"justincarlson7@gmail.com",	"919-880-8005",	2,	"monthly", FALSE);